### PR TITLE
Fixes pcap_replay experiment timeout

### PR DESCRIPTION
**Pull request by akshayeshenoi**
Fixes a bug that was causing the binary to quit prematurely over [here](https://github.com/shadow/shadow-plugin-extras/compare/master...akshayeshenoi:master#diff-61a577e12f072aacadd136a5e0d5c1ee3117b190b09db44c39afae030ced43b8L173).

Added a few other enhancements.

### CODE REVIEW

**Review by robgjansen — COMMENTED** [review]
Looks reasonable to me!

I'm curious, were these changes tested in the shadow version too? Or only in the executable version outside of shadow?

**Comment by akshayeshenoi** [comment]
I’ve tested it on both scenarios: on shadow and outside of shadow. 

On a side note, I think the example currently bundled with the tool is outdated (it uses an older `shadow.xml` syntax). Maybe I’ll update that later.

**Comment by robgjansen** [comment]
> On a side note, I think the example currently bundled with the tool is outdated (it uses an older shadow.xml syntax). Maybe I’ll update that later.

Would you be willing to do that now as part of this pull request? I also think we need to update the README to show which version and commit of Shadow it was tested and known to be working (in the `Last known working version` section of the README).

**Comment by akshayeshenoi** [comment]
Hope this helps!

**Comment by robgjansen** [comment]
The updates to the docs are great, thank you!

My last remaining concern is the example file is a 9 MB binary, primarily due to a large pcap file inside the tar. Is there any way we can get by with a smaller pcap file instead (I'm thinking at most ~1 MB, but smaller is better)?

**Comment by akshayeshenoi** [comment]
Sure, that makes sense.

I have trimmed the pcap file.

**Pull request merged**
